export const FETCH_ALL_MOVIES_REQUEST = "FETCH_ALL_MOVIES_REQUEST";
export const FETCH_ALL_MOVIES_SUCCESS = "FETCH_ALL_MOVIES_SUCCESS";
export const FETCH_ALL_MOVIES_ERROR = "FETCH_ALL_MOVIES_ERROR";

export const FAVOURITE_MOVIES_REQUEST = "FAVOURITE_MOVIES_REQUEST";
export const FAVOURITE_MOVIES_SUCCESS = "FAVOURITE_MOVIES_SUCCESS";
export const FAVOURITE_MOVIES_ERROR = "FAVOURITE_MOVIES_ERROR";

export const RATING_MOVIES_REQUEST = "RATING_MOVIES_REQUEST";
export const RATING_MOVIES_SUCCESS = "RATING_MOVIES_SUCCESS";
export const RATING_MOVIES_ERROR = "RATING_MOVIES_ERROR";

export const HIDE_MOVIES_REQUEST = "HIDE_MOVIES_REQUEST";
export const HIDE_MOVIES_SUCCESS = "HIDE_MOVIES_SUCCESS";
export const HIDE_MOVIES_ERROR = "HIDE_MOVIES_ERROR";

export const DELETE_MOVIES_REQUEST = "DELETE_MOVIES_REQUEST";
export const DELETE_MOVIES_SUCCESS = "DELETE_MOVIES_SUCCESS";
export const DELETE_MOVIES_ERROR = "DELETE_MOVIES_ERROR";