export const FETCH_ALL_MOVIES_REQUEST = "FETCH_ALL_MOVIES_REQUEST";
export const FETCH_ALL_MOVIES_SUCCESS = "FETCH_ALL_MOVIES_SUCCESS";
export const FETCH_ALL_MOVIES_ERROR = "FETCH_ALL_MOVIES_ERROR";

export const FAVOURITE_MOVIES_REQUEST = "FAVOURITE_MOVIES_REQUEST";
export const FAVOURITE_MOVIES_SUCCESS = "FAVOURITE_MOVIES_SUCCESS";
export const FAVOURITE_MOVIES_ERROR = "FAVOURITE_MOVIES_ERROR";

export const RATING_MOVIES_REQUEST = "RATING_MOVIES_REQUEST";
export const RATING_MOVIES_SUCCESS = "RATING_MOVIES_SUCCESS";
export const RATING_MOVIES_ERROR = "RATING_MOVIES_ERROR";